---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u sanjuds888@gmail.com -p Sanjuds888 jfrogsangeetha123.jfrog.io 
    
    - name: pull an image
      shell: docker pull jfrogsangeetha123.jfrog.io/dockerrepo/frontend/test-managment:{{ BUILD_NUMBER }}

    #- name: remove container
      #shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8081 jfrogsangeetha123.jfrog.io/dockerrepo/frontend/test-managment:{{ BUILD_NUMBER }}
 
   
